torque_constant:
   arm_1_joint: 0.0735
   arm_2_joint: 0.0735
   arm_3_joint: -0.1149
   arm_4_joint: -0.1149
   arm_5_joint: 0.0 # 0.0487
   arm_6_joint: 0.0 # 0.0487
   arm_7_joint: 0.0 # 0.0487


torque_control:
  type: "walking_force_control/ArmTorqueControlComand"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint

  base_link_name: "base_link"
  reference_signal: "circle"
  tip_link_name: "arm_7_link"
  hardware: True
  dt: 0.005


controller_params:
   torque_scaling_0: 1.0
   viscous_friction_0: 2.1
   static_friction_0: 0.5
   torque_scaling_1: 1.5
   viscous_friction_1: 1.7
   static_friction_1: 0.6 
   torque_scaling_2: 1.0
   viscous_friction_2: 2.3
   static_friction_2: 0.8
   torque_scaling_3: 1.0
   viscous_friction_3: 2.0
   static_friction_3: 0.5

gravity_compensation:
  type: "walking_force_control/GravityCompensation"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
#    - arm_left_5_joint
#    - arm_left_6_joint
#    - arm_left_7_joint
  reference_signal: "circle"
  base_link_name: "base_link"
  tip_link_name: "arm_7_link"
  hardware: True

  friction:
   arm_1_joint: {s: 3.1, v: 0.4}
   arm_2_joint: {s: 3.1, v: 0.4}
   arm_3_joint: {s: 3.1, v: 0.4}
   arm_4_joint: {s: 1.3, v: 0.4}
   arm_5_joint: &default_friction {s: 0, v: 0}
   arm_6_joint: *default_friction
   arm_7_joint: *default_friction
   head_1_joint: *default_friction
   head_2_joint: *default_friction
   torso_lift_joint: *default_friction
   caster_back_left_1_joint: *default_friction
   caster_back_left_2_joint: *default_friction
   caster_back_right_1_joint: *default_friction
   caster_back_right_2_joint: *default_friction
   caster_front_right_1_joint: *default_friction
   caster_front_right_2_joint: *default_friction
   caster_front_left_1_joint: *default_friction
   caster_front_left_2_joint: *default_friction
   wheel_left_joint: *default_friction
   wheel_right_joint: *default_friction
   hand_index_abd_joint: *default_friction
   hand_index_virtual_1_joint: *default_friction
   hand_index_flex_1_joint: *default_friction
   hand_index_virtual_2_joint: *default_friction
   hand_index_flex_2_joint: *default_friction
   hand_index_virtual_3_joint: *default_friction
   hand_index_flex_3_joint: *default_friction
   hand_index_joint: *default_friction
   hand_little_abd_joint: *default_friction
   hand_little_virtual_1_joint: *default_friction
   hand_little_flex_1_joint: *default_friction
   hand_little_virtual_2_joint: *default_friction
   hand_little_flex_2_joint: *default_friction
   hand_little_virtual_3_joint: *default_friction
   hand_little_flex_3_joint: *default_friction
   hand_middle_abd_joint: *default_friction
   hand_middle_virtual_1_joint: *default_friction
   hand_middle_flex_1_joint: *default_friction
   hand_middle_virtual_2_joint: *default_friction
   hand_middle_flex_2_joint: *default_friction
   hand_middle_virtual_3_joint: *default_friction
   hand_middle_flex_3_joint: *default_friction
   hand_mrl_joint: *default_friction
   hand_ring_abd_joint: *default_friction
   hand_ring_virtual_1_joint: *default_friction
   hand_ring_flex_1_joint: *default_friction
   hand_ring_virtual_2_joint: *default_friction
   hand_ring_flex_2_joint: *default_friction
   hand_ring_virtual_3_joint: *default_friction
   hand_ring_flex_3_joint: *default_friction
   hand_thumb_abd_joint: *default_friction
   hand_thumb_virtual_1_joint: *default_friction
   hand_thumb_flex_1_joint: *default_friction
   hand_thumb_virtual_2_joint: *default_friction
   hand_thumb_flex_2_joint: *default_friction
   hand_thumb_joint: *default_friction



wrist_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
  constraints:
    goal_time:  0.6
    stopped_velocity_tolerance: 0.05
    arm_left_5_joint:
      goal: &goal_pos_constraint 0.02
    arm_left_6_joint:
      goal: *goal_pos_constraint
    arm_left_7_joint:
      goal: *goal_pos_constraint

wrist_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_5_motor
    - arm_6_motor
    - arm_7_motor

